version: 2

builds:
  - id: agent
    main: ./cmd/nodeattestor-pkcs11-agent
    binary: spire-plugin-pkcs11-agent
    env: [CGO_ENABLED=0]
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]

  - id: server
    main: ./cmd/nodeattestor-pkcs11-server
    binary: spire-plugin-pkcs11-server
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]

archives:
  - id: agent
    ids: [agent]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "spire-plugin-pkcs11-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: server
    ids: [server]
    formats: [tar.gz]
    name_template: "spire-plugin-pkcs11-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore\\(deps\\):"
      - "^ci:"
